# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('sap', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=2000)),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('bday', models.DateField()),
                ('year', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=15)),
                ('division', models.CharField(max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('is_submitted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.Details')),
            ],
        ),
    ]
