# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0003_auto_20170319_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='sap',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
